language: c
sudo: True

## 'os' selection needs to be enabled manually by emailing travis-ci
os:
  - linux
  - osx

before_install:
- mkdir -p $(pwd)/build
- ./kitchen/ingredients.sh
- make -C build -f $(pwd)/kitchen/cook DESTDIR=$(pwd)/dist TARGETOS=$(./kitchen/mangle_os.sh ${TRAVIS_OS_NAME}) PDDIR=$(pwd)/build/pd/ PDINCLUDE=$(pwd)/build/pd/src depends
script:
- make -C build -f $(pwd)/kitchen/cook DESTDIR=$(pwd)/dist TARGETOS=$(./kitchen/mangle_os.sh ${TRAVIS_OS_NAME}) PDDIR=$(pwd)/build/pd/ PDINCLUDE=$(pwd)/build/pd/src build install
