#!/bin/sh

error() {
  echo "$@" 1>&2
}
usage() {
 error "usage: $0 [-s <OperatingSystem>] [-p <PdDir>]"
 error "     <OperatingSystem>: either 'osx' or 'w32'"
 error "     <PdDir>: installation path of Pd-Resources"
 error "	default: fetches an separate Pd"
 exit $1
}

RUNDIR=$(pwd)
SCRIPTDIR=${0%/*}/
cd "${SCRIPTDIR}"
SCRIPTDIR=$(pwd)
cd "${SCRIPTDIR}/../build"
BUILDDIR=$(pwd)
cd "${RUNDIR}"

PDDIR=${BUILDDIR}/pd
OS=
if [ "x${TRAVIS_OS_NAME}" != "x" ]; then
 OS=$(${SCRIPTDIR}/closet/mangle_os.sh ${TRAVIS_OS_NAME})
fi

while getopts "s:p:" opt; do
 case $opt in
   s)
     OS=$OPTARG
     ;;
   p)
     PDDIR=$OPTARG
     ;;
   h|\?)
     usage 0
     ;;
   :)
     error "Option -${OPTARG} requires an argument"
     exit 1
     ;;
   *)
     error "fallback: $OPTARG"
     ;;
  esac
done
shift $(( ${OPTIND} - 1 ))

if [ "x${OS}" = "x" ]; then
  usage 1
fi


